### ISSUE TITLE
Rave not working on my php version

### ISSUE THREAD

**Issue by Akinrinadegreat1** [bosunolanrewaju/wp-rave-payment-forms#1]
I'm using a server that is running on Php version 5.2.17. Which at later, giving me a fatal error display message. Please what's the way out?

**Comment by bosunolanrewaju** [comment]
@Akinrinadegreat1 Could you please provide the fatal error you got? Just copy and paste here.

**Comment by Akinrinadegreat1** [comment]
Fatal error: call to undefined function openssl_random_pseudo_bytes() in /home/content/59/7274659/html/mts/wp-content/phpform.php on line 4

**Comment by Akinrinadegreat1** [comment]
Fatal error: Call to undefined function openssl_random_pseudo_bytes() in /home/content/59/7274659/html/mts/wp-content/plugins/wp-rave-payment-forms-master/views/pay-now-form.php on line 4

**Comment by Akinrinadegreat1** [comment]
The last message is the correct fatal error code

**Comment by bosunolanrewaju** [comment]
Oh, I see. PHP Version issue there. I will make a fallback fix for that and let you know. Thanks

**Comment by Akinrinadegreat1** [comment]
Ok. Thanks. Like how soon, please?

**Comment by bosunolanrewaju** [comment]
@Akinrinadegreat1 please I have made the fix. Try it now

**Comment by Akinrinadegreat1** [comment]
ok

**Comment by Akinrinadegreat1** [comment]
Still Fatal error: Call to undefined function openssl_random_pseudo_bytes() in /home/content/59/7274659/html/mts/wp-content/plugins/wp-rave-payment-forms-master/views/pay-now-form.php on line 4

**Comment by bosunolanrewaju** [comment]
Please deactivate the plugin from your WordPress dashboard and delete it. Then download a fresh zip and install.

**Comment by Akinrinadegreat1** [comment]
thanks it works . great job . I will like to know if the short code can works as : www.thrivesend.com where on the Amount to send  and send Money button is available

**Comment by Akinrinadegreat1** [comment]
how can I fix the css or add the plugins

**Comment by bosunolanrewaju** [comment]
@Akinrinadegreat1 I don't understand your question. Can you be more elaborate? What do you want the plugin to do?

**Comment by Akinrinadegreat1** [comment]
casade style sheet  how can it be edited for the bottom

**Comment by Akinrinadegreat1** [comment]
Styling

You can enable default theme's style to override default form style from the Settings page. Or you can override the form class .flw-simple-pay-now-form from your stylesheet.

I can not locate this file in the settings

**Comment by bosunolanrewaju** [comment]
> Or you can override the form class .flw-simple-pay-now-form from your stylesheet.

What that statement means is that you can override the default style by setting your own style on `.flw-simple-pay-now-form` css class in your stylesheet or current theme's custom style option.

I could probably add a text area element in the settings for users to set custom styling directly. For now, you can only override the default styling class `.flw-simple-pay-now-form` through current theme's custom style or you create a stylesheet file.

**Comment by Akinrinadegreat1** [comment]
thanks

**Comment by Akinrinadegreat1** [comment]
HOW DO i REMOVE THE EMAIL FROM THE PLUGIN

**Comment by bosunolanrewaju** [comment]
@Akinrinadegreat1 What email do you want to remove, please? Follow the steps in the documentation. If there is a new behavior that you would like to see, raise it an issue and specify that it is a feature request or suggestion.

**Comment by Akinrinadegreat1** [comment]
[flw-pay-button amount=""  ]SEND MONEY[/flw-pay-button]

**Comment by Akinrinadegreat1** [comment]
[flw-pay-button amount="" email="customer@email.com" ]Button Text[/flw-pay-button] 

THIS WORKS BUT NOT IN DOCUMENTATION

**Comment by bosunolanrewaju** [comment]
@Akinrinadegreat1  Rave requires that the user making the payment supply either email or phone number for identification. I used email because I believe people feel more comfortable in giving out their email.

In your case, if you don't want to display the email field, you can tell the plugin to use the logged in user's email. This means that the user needs to log in. If the user is not logged in, the email field will be displayed.

**Comment by bosunolanrewaju** [comment]
> THIS WORKS BUT NOT IN DOCUMENTATION

It is in the documentation under [shortcode](https://github.com/bosunolanrewaju/wp-rave-payment-forms#1-shortcode) section

**Comment by Akinrinadegreat1** [comment]
Good morning ,
Please kindly update me on how to fix the moneywave in to my website. Thanks

**Comment by bosunolanrewaju** [comment]
@Akinrinadegreat1 please talk to moneywave support for that.
