### ISSUE TITLE
RavePay Shortcodes Not Working

### ISSUE THREAD

**Issue by adizos** [bosunolanrewaju/wp-rave-payment-forms#11]
Thanks for a wonderful payment plugin. After installing the rave payment forms and added the shortcode to a WordPress page it showed up blank when I viewed the page. The form was not displayed at all on the page.
Also as part of update, it will be interesting to integrate with popular WP forms or upgrade the forms such that one can set various preset amount for payments as well as open amount where the user enters the amount top pay.

**Comment by bosunolanrewaju** [comment]
@adizos Can you confirm that you have added your Ravepay public and secret key to the plugin settings page? The form will not display if the public key and secret key is not set.

As for the update part, the form currently has that feature. You can set an amount for the user to pay.
 
This `[flw-pay-button amount="1290" email="customer@email.com" ]` lets you set fixed amount **1290** and fixed email for the form. While `[flw-pay-button use_current_user_email="yes" ]` will make the form display only the amount field for the user to fill in the value and use the logged in user's email address if the user is logged in. If the user is not logged in, it will also display an email field for the user to enter their email.

Let me know if this helps.

**Comment by muaad** [comment]
@bosunolanrewaju I have a similar issue. The short code is just displayed on the page but there is no form. And, I have the public and secret keys setup.
