### ISSUE TITLE
Integrate with WooCommerce

### ISSUE THREAD

**Issue by DonJyde** [bosunolanrewaju/wp-rave-payment-forms#12]
I think you should enable it to integrate with woocommerce.
It does not seem to work woocommerce for now

**Comment by bosunolanrewaju** [comment]
@DonJyde Thanks for your suggestion. There is a separate plugin to integrate Rave with  WooCommerce. Check the plugin [here](https://github.com/bosunolanrewaju/WooCommerce-Rave-Payment-Gateway)
