### ISSUE TITLE
[wp-rave-payment-forms-test-go-live  ] Installing this give the below error.

### ISSUE THREAD

**Issue by Akinrinadegreat1** [bosunolanrewaju/wp-rave-payment-forms#4]
Parse error: syntax error, unexpected '[' in /home/content/59/7274659/html/mts/wp-content/plugins/wp-rave-payment-forms-test-go-live/includes/rave-base-class.php on line 167

Please help to resolve this . Thanks

**Comment by bosunolanrewaju** [comment]
@Akinrinadegreat1 thanks for reporting, it is the backward compatibility issue again. I made a fix on the same branch. Download and replace existing plugin with the fixed one.

**Comment by bosunolanrewaju** [comment]
@Akinrinadegreat1 Just checking up on this issue, have you tried the fix? Let me know so I can close this issue.
